-- 실내 공기
CREATE TABLE air_quality (
	AIR_NO INT AUTO_INCREMENT PRIMARY KEY
	, PM_CODE INT NOT NULL
	, PM_GRADE VARCHAR(10) DEFAULT '보통' -- 좋음, 보통, 나쁨, 매우 나쁨
	, FPM_CODE INT NOT NULL
	, FPM_GRADE VARCHAR(10) DEFAULT '보통' -- 좋음, 보통, 나쁨, 매우 나쁨
	, CO2_CODE FLOAT NOT NULL
	, VOCS_CODE INT NOT NULL
	, AIR_TIME DATETIME NOT NULL
	, SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
);

DROP TABLE air_quality;

-- ALTER TABLE air_quality ADD COLUMN AIR_TIME DATETIME NOT NULL AFTER VOCS_CODE;


-- 실내통합지수
CREATE TABLE CICI (
	CICI_NO INT AUTO_INCREMENT PRIMARY KEY
	, CICI_CODE INT NOT NULL
	, CICI_GRADE VARCHAR(10) DEFAULT '보통' -- 좋음, 보통, 나쁨, 매우 나쁨
	, CICI_TIME DATETIME NOT NULL
	, SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
);

DROP TABLE cici;

-- ALTER TABLE CICI ADD COLUMN CICI_TIME DATETIME NOT NULL AFTER CICI_GRADE;

--  REFERENCES MAP (SERIAL_NO)
-- ------------------------------------------------------------------

-- 지도
CREATE TABLE map (
	SERIAL_NO VARCHAR(15) NOT NULL PRIMARY KEY
	, STATION_NAME VARCHAR(20) NOT NULL
	, LAT DOUBLE DEFAULT 37.0000
	, LON DOUBLE DEFAULT 126.0000
);

DROP TABLE map;

WHERE serial_no NOT IN (SELECT DISTINCT serial_no FROM air_quality);
-- ------------------------------------------------------------------

-- 서초구 전체의 데이터 테이블



-- 각 위치의 데시벨 데이터 테이블
CREATE TABLE DECIBEL_INFO (
	DECIBEL_CODE INT AUTO_INCREMENT PRIMARY KEY
	, DECIBEL INT NOT NULL
	, DECIBEL_TIME DATETIME NOT NULL
	, DECIBEL_GRADE VARCHAR(10) NOT NULL DEFAULT '보통' -- '좋음, 보통, 나쁨'
	, SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
);

DROP TABLE DECIBEL_INFO;

-- ------------------------------------------------------------------

CREATE TABLE AVERAGE (
	AVERAGE_CODE INT AUTO_INCREMENT PRIMARY KEY
	, AVERAGE_RESULT DOUBLE
	, AVERAGE_NAME VARCHAR(20) NOT NULL
);

DROP TABLE AVERAGE;

-- ------------------------------------------------------------------

CREATE TABLE TEMANDHUM (
	DATA_CODE INT AUTO_INCREMENT PRIMARY KEY
	, DATE_TIME DATETIME NOT NULL
	, TEMPERATURE FLOAT NOT NULL
	, HUMIDITY INT NOT NULL
	, SERIAL_NO VARCHAR(20) REFERENCES MAP (SERIAL_NO)
);

DROP TABLE TEMANDHUM;

-- ------------------------------------------------------------------

-- 가장 높은 실내통합지수 top 10  /  달마다....?
SELECT SERIAL_NO
		, CICI_CODE
		, CICI_GRADE
FROM cici
ORDER BY CICI_CODE DESC LIMIT 10;

-- 가장 낮은 실내통합지수 top 10  /  달마다....?
SELECT SERIAL_NO
		, CICI_CODE
		, CICI_GRADE
FROM cici
ORDER BY CICI_CODE ASC LIMIT 10;

