-- 기본키(PRIMARY KEY : PK)
-- NULL이 들어갈 수 없고, 테이블 내에서 중복 불가

-- 회원 정보 테이블
CREATE TABLE BOARD_MEMBER(
	-- 컬럼명 자료형 [제약조건]
	MEMBER_ID VARCHAR(20) PRIMARY KEY
	, MEMBER_PW VARCHAR(20) NOT NULL
	, MEMBER_NAME VARCHAR(20) NOT NULL
	, GENDER VARCHAR(2) -- '남', '여'
	, MEMBER_EMAIL VARCHAR(30) UNIQUE -- 중복되면 곤란하겠지 (UNIQUE)
	, IS_ADMIN VARCHAR(2) DEFAULT 'N'-- 관리자인지 아닌지 구분 'N', 'Y'
);

-- 게시글 정보 테이블
CREATE TABLE BOARD(
	-- WRITER : 외래키(Foreign Key : FK) 제약조건
	-- 컬럼명 자료형 [제약조건]
	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY -- 자동으로 증가 (AUTO_INCREMENT) = CNT++;
	, TITLE VARCHAR(30) NOT NULL
	, CONTENT VARCHAR(100)
	, WRITER VARCHAR(20) REFERENCES board_member (MEMBER_ID)
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, READ_CNT INT DEFAULT 0
);

CREATE TABLE BOARD_REPLY(
	REPLY_NUM INT AUTO_INCREMENT PRIMARY KEY
	, CONTENT VARCHAR(50) NOT NULL
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, WRITER VARCHAR(20) REFERENCES board_member (MEMBER_ID)
	, BOARD_NUM INT REFERENCES board (BOARD_NUM)
)


UPDATE board_member
SET IS_ADMIN = 'Y'
WHERE MEMBER_ID = 'admin';

SELECT * FROM BOARD_REPLY;

ROLLBACK;

COMMIT;
SELECT * FROM board;
SELECT * FROM board_member;



-- 모든 게시글의 
-- 게시글 번호, 제목, 작성자명, 작성자 ID를 조회
SELECT BOARD_NUM
		, TITLE
		, MEMBER_NAME
		, MEMBER_ID
FROM board INNER JOIN BOARD_MEMBER
ON WRITER = MEMBER_ID



SELECT *
FROM board
ORDER BY BOARD_NUM
LIMIT 5 OFFSET 10;



SELECT COUNT(*) FROM emp; 








