-- 기본 게시판 테이블
CREATE TABLE BASIC_BOARD(
	BOARD_NUM INT PRIMARY KEY -- NOT NULL, 중복x
	, BOARD_TITLE VARCHAR(50) NOT NULL
	, BOARD_CONTENT VARCHAR(50)
	, WRITER VARCHAR(20) NOT NULL
	, CREATE_DATE VARCHAR(20) NOT NULL -- '2023-05-10'
	, READ_CNT INT DEFAULT 0
);

SELECT * FROM basic_board;

UPDATE 문법
UPDATE basic_board
SET
WRITER = '김자바';
, BOARD_CONTENT = '변경내용'
WHERE BOARD_NUM=1;



COMMIT;
ROLLBACK;

board_member