CREATE TABLE STUDYROOM_CHARGE (
	CHARGE_CODE INT PRIMARY KEY
	, CHARGE_FEE INT NOT NULL
	, CHARGE_DATE DATETIME NOT NULL
);

CREATE TABLE STUDYROOM_MESSAGE (
	MESSAGE_CODE INT PRIMARY KEY
	, MESSAGE_CONTENT VARCHAR(300) NOT NULL
	, MESSAGE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, MEMBER_CODE INT 
	, SEAT_NUM INT
);

SELECT * FROM STUDYROOM_MESSAGE;