-- 자동차 정보
CREATE TABLE CAR_INFO (
	MODEL_NUMBER INT AUTO_INCREMENT PRIMARY KEY
	, MODEL_NAME VARCHAR(30) NOT NULL
	, PRICE INT NOT NULL
	, MAKER VARCHAR(30) NOT NULL
);

SELECT * FROM CAR_INFO;


-- 자동차 판매정보
CREATE TABLE SALES_INFO (
	SALES_NUMBER INT AUTO_INCREMENT PRIMARY KEY
	, CUSTOMER_NAME VARCHAR(20) NOT NULL
	, CUSTOMER_TEL VARCHAR(50)
	, CAR_COLOR VARCHAR(20) NOT NULL
	, SALES_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	, MODEL_NUMBER INT NOT NULL
);

SELECT * FROM sales_info;

-- 미리 하나 등록해놓기
INSERT INTO CAR_INFO VALUES (1, 'DH-3321', 3200000, '현대');
COMMIT;

 SELECT MODEL_NUMBER
        , MODEL_NAME
        , MAKER
        FROM car_info;
        
        
-- 테스트 (문제없음)
SELECT SALES.MODEL_NUMBER
            , CUSTOMER_NAME
            , CUSTOMER_TEL
            , SALES_DATE
            , CAR_COLOR
            , MODEL_NAME
            , PRICE
        FROM SALES_INFO SALES INNER JOIN CAR_INFO CAR
        ON SALES.MODEL_NUMBER = CAR.MODEL_NUMBER;