-- 자동차 정보
CREATE TABLE CAR_INFO (
	MODEL_NUMBER INT PRIMARY KEY AUTO_INCREMENT
	, MODEL_NAME VARCHAR(30) NOT NULL
	, PRICE INT NOT NULL
	, MAKER VARCHAR(30) NOT NULL
);

SELECT * FROM CAR_INFO;


-- 자동차 판매정보
CREATE TABLE SALES_INFO (
	SALES_NUMBER INT PRIMARY KEY AUTO_INCREMENT
	, CUSTOMER_NAME VARCHAR(20) NOT NULL
	, CUSTOMER_TEL VARCHAR(50)
	, CAR_COLOR VARCHAR(20) NOT NULL
	, SALES_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	, MODEL_NUMBER INT NOT NULL
);

SELECT * FROM CAR_INFO;