SELECT MESSAGE_CONTENT
      , SEAT_NUM
      , MESSAGE.MEMBER_CODE
      , MEMBER_NAME
      , MESSAGE_DATE
FROM STUDYROOM_MESSAGE MESSAGE INNER JOIN STUDYROOM_MEMBER MEMBER
ON MESSAGE.MEMBER_CODE = MEMBER.MEMBER_CODE;

-- 이런식으로
-- 장바구니와 관련된 모든 정보를 조회할 수 있는 cart_view 생성
CREATE OR REPLACE VIEW CART_VIEW
AS
SELECT CART_CODE
	, CART.ITEM_CODE
	, CART.MEMBER_ID
	, CART_CNT
	, CART_DATE
	
	, ITEM_NAME
	, ITEM_PRICE
	, ITEM_INTRO
	, ITEM_PRICE * CART_CNT TOTAL_PRICE
	
	, MEMBER_NAME
	, MEMBER_TEL
   , CONCAT(POST_CODE, ' ',MEMBER_ADDR, ' ',ADDR_DETAIL) ADDRESS
   
   , ATTACHED_FILE_NAME
   , ORIGIN_FILE_NAME
   , IS_MAIN
   , IMG_CODE
   
   , ITEM.CATE_CODE
   , CATE_NAME
FROM shop_cart CART
INNER JOIN shop_item ITEM
ON CART.ITEM_CODE = ITEM.ITEM_CODE
INNER JOIN shop_member MEMBER
ON MEMBER.MEMBER_ID = CART.MEMBER_ID
INNER JOIN item_image IMG
ON IMG.ITEM_CODE = ITEM.ITEM_CODE
INNER JOIN item_category CATE
ON CATE.CATE_CODE = ITEM.CATE_CODE
WHERE IS_MAIN = 'Y';


SELECT MEMBER_NAME
		, MEMBER_ID
		, MEMBER_GENDER
		, MEMBER_TEL
		, MEMBER_ADDR
		, MEMBER_DETAIL
		, IS_ADMIN
FROM studyroom_member;

SELECT  MEMBER_NAME
		, MEMBER_ID
		, MEMBER_CODE
FROM studyroom_member;


SELECT MESSAGE_CONTENT
            , MESSAGE.MEMBER_CODE
            , MESSAGE_DATE
        FROM STUDYROOM_MESSAGE MESSAGE INNER JOIN STUDYROOM_MEMBER MEMBER
        ON MESSAGE.MEMBER_CODE = MEMBER.MEMBER_CODE;
        
 SELECT MESSAGE_CONTENT
            , SEAT_NUM
            , MESSAGE.MEMBER_CODE
            , MEMBER_NAME
            , IS_ADMIN
            , MESSAGE_DATE
        FROM STUDYROOM_MESSAGE MESSAGE INNER JOIN STUDYROOM_MEMBER MEMBER
        ON MESSAGE.MEMBER_CODE = MEMBER.MEMBER_CODE;
        
        
SELECT * FROM SECURITY_MEMBER;

-- USER, MANAGER, ADMIN
CREATE TABLE SECURITY_MEMBER (
	MEMBER_ID VARCHAR(50) PRIMARY KEY
	, MEMBER_NAME VARCHAR(50) NOT NULL
	, MEMBER_PW VARCHAR(100) NOT NULL
	, MEMBER_ROLL VARCHAR(50) DEFAULT 'USER'
);

UPDATE security_member
SET MEMBER_ROLL = 'MANAGER'
WHERE MEMBER_ID = 'MANAGER';
COMMIT;